### PR TITLE
Update react-native-web to 0.0.73

### PR DESCRIPTION
**Pull request by AlanFoster**
I would like to have access to `Button` for a react-native presentation, which is available when bumping the `react-native-web` version.

Let me know if there's anything else missing as part of this PR :+1:

### CODE REVIEW

**Comment by AlanFoster** [comment]
When playing around with this, it seems possible to trigger the following error:

```
TypeError: Cannot read property 'getHostNode' of null
Show Details
```

I'm not sure if this is related to the version bump or not. The reproduction steps are currently unclear, but it breaks whilst progressively editing code - and a page refresh fixes the issue.

**Comment by dabbott** [comment]
Hmmm, I'm not sure either.

I think you'll want to upgrade `react` and `react-dom` to whatever version `react-native-web@0.0.73` uses (15.4.1?)

Also I would remove the `^` from `^0.0.73` to lock down the version, in case people install via `npm`. Patch versions aren't *really* patch versions here, since they contain API changes and other potentially breaking things.

After you update, I can play around with it too and try to figure out what's going on.

**Comment by morenogiudici** [comment]
I just updated the package.json file:
    "react": "~15.4.1",
    "react-dom": "~15.4.1",
    "react-native-web": "^0.0.94",
 and everything seems to work

**Comment by necolas** [comment]
👍 latest versions are now react(-dom)@15.5 and react-native-web@0.0.97

**Comment by dabbott** [comment]
Versions have been updated:

```
"react": "^16.2.0"
"react-dom": "^16.2.0"
"react-native-web": "0.5.3"
```

**Pull request closed without merging**
